trigger: none
pool: scanning
stages:
  - stage: 
    displayName: terraform_tool
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/module'
            backendServiceArm: 'scanning_tool'
            backendAzureRmResourceGroupName: 'ravinder_storage'
            backendAzureRmStorageAccountName: 'ravinderstg'
            backendAzureRmContainerName: 'ravindercon'
            backendAzureRmKey: 'ravi.tfstate'
        - task: tfsec@1
          displayName: tfsec-scanning
          continueOnError: true
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)'
        - task: TerraformTask@5
          displayName: plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/module'
            environmentServiceNameAzureRM: 'scanning_tool'      
        - task: TerraformTask@5
          displayName: init2
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/module'
            backendServiceArm: 'scanning_tool'
            backendAzureRmResourceGroupName: 'ravinder_storage'
            backendAzureRmStorageAccountName: 'ravinderstg'
            backendAzureRmContainerName: 'ravindercon'
            backendAzureRmKey: 'ravi.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/module'
            environmentServiceNameAzureRM: 'scanning_tool'
        